Between March 31 and June 30, state average PLRS significantly increases. Appendix A tables. I have made and graphed the changes (focused on 2017 because the interim March data from 2016 is not available).  

- How much does it increase? 
- Does it increase for every state? 
- What are the year to year differences in June 30 scores?



I read the paper on PLRS (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4214270/) twice and I have not found any indication of how it is billed, whether upcoding or downcoding patient issues exist. What I understand is that the government gives the values, based on reported diagnoses. This lends itself to upcoding, or reporting more illnesses to try to game more money from the risk transfer system (6 to 16% higher risk scores in private versus public Medicare plans http://www.nber.org/papers/w21222). So, I believe is in an insurer's best interest to bill for a heart attack every year after the patient has a heart attack. Just like many of the other assumptions that the risk transfer formula was based on, these seem unfounded. To support this, an outside consultant Milliman says the following: "When working with a particular coding vendor (or in house) to develop a coding improvement effort, it is important to be realistic regarding the gain that should be expected in a carrier's risk score. There are many ways to estimate the potential for coding improvement" which pretty explicitly says that an insurer can gain by manipulating a risk score (http://www.milliman.com/uploadedFiles/insight/2016/2157HDP_20160127_value-of-aca-coding.pdf).  I wonder which insurers are aware of this and which ones are not. At the same time, if all insurers are greedy (a rational assumption) and 

Looking at year to year MLR,

Absolute transfers over premiums per state:

In [1]:
import pandas as pd

In [16]:
transfers = pd.read_csv("absolutetransfersperstate2.csv", low_memory=False)
plrs = pd.read_csv("2017data.csv", low_memory=False)

In [17]:

transfers = transfers.apply(pd.to_numeric, errors='ignore')

In [18]:
transfers.head()

,HIOS ID,HIOS INPUTTED INSURANCE COMPANY NAME,STATE,REINSURANCE PAYMENT AMOUNT (OR NOT ELIGIBLE),"HHS RISK ADJUSTMENT TRANSFER AMOUNT (INDIVIDUAL MARKET, INCLUDING CATASTROPHIC)",HHS RISK ADJUSTMENT TRANSFERS AMOUNT (SMALL GROUP MARKET),ABSOLUTE RISK ADJUSTMENT INDIVIDUAL MARKET,ABSOLUTE RISK ADJUSTMENT SMALL GROUP MARKET
0,11082,Aetna Life Insurance Company,AK,N/E,$-,-1188058.34,#VALUE!,1188058.34
1,38344,Premera Blue Cross,AK,5758679.10,11418310.79,4017476.01,11418310.79,4017476.01
2,73836,Moda Health Plan Inc,AK,8987021.64,-11418310.77,-2026261.96,11418310.77,2026261.96
3,80049,UnitedHealthcare Insurance Company,AK,N/E,$-,-803155.69,#VALUE!,803155.69
4,44580,Humana Insurance Company,AL,2298478.10,-13518890.18,$-,13518890.18,#VALUE!

In [4]:
plrs.head()

,State,STATE AVERAGE MONTHLY PREMIUMS Individual,STATE AVERAGE PLAN LIABILITY RISK SCORE Individual,STATE AVERAGE ALLOWABLE RATING FACTOR Individual,STATE AVERAGE ACTUARIAL VALUE Individual,STATE INDUCED DEMAND FACTOR Individual,STATE BILLABLE MEMBER MONTHS Individual,STATE AVERAGE MONTHLY PREMIUMS Small Group,STATE AVERAGE PLAN LIABILITY RISK SCORE Small Group,STATE AVERAGE ALLOWABLE RATING FACTOR Small Group,STATE AVERAGE ACTUARIAL VALUE Small Group,STATE INDUCED DEMAND FACTOR Small Group,STATE BILLABLE MEMBER MONTHS Small Group
0,AK,871.22,1.47,1.62,0.65,1.02,208994.07,668.91,1.12,1.42,0.70,1.04,133581.1
1,AL,408.03,2.01,1.59,0.70,1.03,2498322.17,412.51,1.57,1.46,0.78,1.07,2493431.5
2,AR,369.25,2.05,1.48,0.70,1.03,3996773.67,383.75,1.37,1.41,0.79,1.08,283760.7
3,AZ,321.39,1.52,1.54,0.68,1.03,2724664.80,374.00,1.22,1.37,0.73,1.05,1522128.7
4,CA,393.25,1.35,1.57,0.70,1.04,25466502.60,434.42,1.16,1.37,0.76,1.07,21838121.8

In [36]:
states = plrs["State"]
cols = ['State', 'Absolute Risk Adjustment Individual Market', 'Absolute Risk Adjustment Small Group Market']
payment_sum = pd.DataFrame(columns=cols)
payment_sum.loc[0] = [1.0, 'hotel', 'true']
print(payment_sum)

   State Absolute Risk Adjustment Individual Market  \
0    1.0                                      hotel

  Absolute Risk Adjustment Small Group Market
0                                        true

In [37]:
i = 0
for state in states:
    temp = transfers.where(transfers["STATE"] == state).dropna()
    a = sum(temp["ABSOLUTE RISK ADJUSTMENT INDIVIDUAL MARKET"].convert_objects(convert_numeric=True).dropna())
    b = sum(temp["ABSOLUTE RISK ADJUSTMENT SMALL GROUP MARKET"].convert_objects(convert_numeric=True).dropna())
    new_row = [state, a, b]
    payment_sum.loc[i] = new_row
    print(state + " " + str(a) + " " + str(b))
    i = i + 1

C:\Users\guanz\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  after removing the cwd from sys.path.
C:\Users\guanz\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """

AK 22836621.56 8034952.0
AL 49878797.63 4589684.4
AR 18067737.62 3711497.21
AZ 109239657.37 26923715.19
CA 785430191.5 749549408.13
CO 174994535.39 44757300.12
CT 58610590.68 52491672.13
DC 19620343.9 34123766.84
DE 3332850.5 1777938.52
FL 1150759937.0 79903247.44
GA 353771240.47 39540532.96
HI 33023787.55 23772754.75
IA 37893103.49 12357587.87
ID 29989532.11 6752087.06
IL 197552212.93 28090507.32
IN 120965262.71 25488531.61
KS 92436030.39 8074692.66
KY 36299885.01 15904928.1
LA 205389157.02 20671147.6
MD 87984755.39 60647128.88
ME 11852968.85 9519113.36
MI 261910927.78 61478001.13
MN 228844026.92 56532021.57
MO 91763420.45 21144797.08
MS 32090280.93 1790888.8
MT 10675807.43 739201.11
NC 301275625.47 41379576.03
ND 10900109.23 3105755.44
NE 49543525.11 10134693.82
NH 51751774.01 12312433.63
NJ 232348425.38 75427092.58
NM 14950690.95 18403686.84
NV 46751824.46 16196224.91
NY 388355722.51 568146455.21
OH 140350493.16 65897194.14
OK 10021864.21 19199427.94
OR 101943161.39 22181098.51
PA 302725439.15 98802831.29
RI 12055421.82 16160217.66
SC 26484984.76 14214306.71
SD 16869212.82 4261807.83
TN 83670311.79 14474409.76
TX 586308266.47 96386650.83
UT 77960967.76 10644819.46
VA 193682799.25 95413713.45
WA 170550334.28 33369146.74
WI 140052967.0 42931228.2
WV 4816629.01 3844110.21
WY 16978.58 2716182.83

In [39]:
payment_sum.head()

,State,Absolute Risk Adjustment Individual Market,Absolute Risk Adjustment Small Group Market
0,AK,2.28366e+07,8.03495e+06
1,AL,4.98788e+07,4.58968e+06
2,AR,1.80677e+07,3.7115e+06
3,AZ,1.0924e+08,2.69237e+07
4,CA,7.8543e+08,7.49549e+08

In [40]:
total = pd.merge(payment_sum, plrs, on='State')

In [41]:
total.head()

,State,Absolute Risk Adjustment Individual Market,Absolute Risk Adjustment Small Group Market,STATE AVERAGE MONTHLY PREMIUMS Individual,STATE AVERAGE PLAN LIABILITY RISK SCORE Individual,STATE AVERAGE ALLOWABLE RATING FACTOR Individual,STATE AVERAGE ACTUARIAL VALUE Individual,STATE INDUCED DEMAND FACTOR Individual,STATE BILLABLE MEMBER MONTHS Individual,STATE AVERAGE MONTHLY PREMIUMS Small Group,STATE AVERAGE PLAN LIABILITY RISK SCORE Small Group,STATE AVERAGE ALLOWABLE RATING FACTOR Small Group,STATE AVERAGE ACTUARIAL VALUE Small Group,STATE INDUCED DEMAND FACTOR Small Group,STATE BILLABLE MEMBER MONTHS Small Group
0,AK,2.28366e+07,8.03495e+06,871.22,1.47,1.62,0.65,1.02,208994.07,668.91,1.12,1.42,0.70,1.04,133581.1
1,AL,4.98788e+07,4.58968e+06,408.03,2.01,1.59,0.70,1.03,2498322.17,412.51,1.57,1.46,0.78,1.07,2493431.5
2,AR,1.80677e+07,3.7115e+06,369.25,2.05,1.48,0.70,1.03,3996773.67,383.75,1.37,1.41,0.79,1.08,283760.7
3,AZ,1.0924e+08,2.69237e+07,321.39,1.52,1.54,0.68,1.03,2724664.80,374.00,1.22,1.37,0.73,1.05,1522128.7
4,CA,7.8543e+08,7.49549e+08,393.25,1.35,1.57,0.70,1.04,25466502.60,434.42,1.16,1.37,0.76,1.07,21838121.8

In [70]:
print("state,individual_ra_premiums_ratio,smallgroup_ra_premiums_ratio")
for state in states:
    thisstate = total.where(total["State"] == state).dropna()
    individual = pd.to_numeric(thisstate["Absolute Risk Adjustment Individual Market"].item()
                               / thisstate["STATE BILLABLE MEMBER MONTHS Individual"].item()
                               / thisstate["STATE AVERAGE MONTHLY PREMIUMS Individual"].item())
    smallgroup = pd.to_numeric(thisstate["Absolute Risk Adjustment Small Group Market"].item()
                               / thisstate["STATE BILLABLE MEMBER MONTHS Small Group"].item()
                               / thisstate[" STATE AVERAGE MONTHLY PREMIUMS Small Group"].item())
    print(state + "," + str(individual) + "," + str(smallgroup))

state,individual_ra_premiums_ratio,smallgroup_ra_premiums_ratio
AK,0.125420940961,0.0899229576223
AL,0.048930025114442895,0.004462219198475682
AR,0.012242601560522547,0.034083838838241905
AZ,0.12474837254025524,0.047294649452947084
CA,0.07842771356909407,0.07900874627816311
CO,0.14758891731833315,0.043359631248616984
CT,0.06522281018889935,0.05155463173186002
DC,0.30790516670046675,0.07507544570623625
DE,0.017126347743423753,0.009268603933780676
FL,0.1500685425820422,0.056933514683589016
GA,0.1367706767486449,0.046966907365244115
HI,0.21946331337059308,0.14513351437173422
IA,0.0945961427232965,0.034539486831202705
ID,0.06089299345887501,0.03936347771194086
IL,0.08992274323994853,0.018674635556482595
IN,0.12318598142166308,0.05443960769064669
KS,0.17449655082938678,0.02908665737838191
KY,0.07964228821792182,0.05883402178266696
LA,0.18683091220865625,0.04085169697606494
MD,0.08681572791189657,0.04652959105933196
ME,0.028954271854564964,0.04085168132497004
MI,0.14291207167926537,0.036824310531226284
MN,0.21486390990667562,0.045417928252996995
MO,0.06803671043346166,0.042326438457662624
MS,0.07478127691278041,0.022712183502474573
MT,0.030287275657515794,0.0034199736311679198
NC,0.09569867922830631,0.06415067008948155
ND,0.054080212875230065,0.021715752477323463
NE,0.09911275174153772,0.049646607741750164
NH,0.11642145642533949,0.04819584301836817
NJ,0.12136082345353441,0.03218459444245418
NM,0.05511010672630783,0.07393519299262094
NV,0.0853685585481368,0.039194599998276826
NY,0.20931805129563344,0.08260970323784875
OH,0.10806545378193225,0.09655838397155411
OK,0.01394770842638787,0.03278024027904296
OR,0.10739366772668478,0.04089901019880432
PA,0.11739850626409926,0.04458593819689395
RI,0.05934466770577408,0.04688359841138635
SC,0.025189154859572134,0.04224329953388159
SD,0.08588317291378388,0.03300088397820626
TN,0.060925266709673784,0.026453614405809657
TX,0.11404028105504911,0.03228787785875251
UT,0.11876995646588863,0.02216989591435411
VA,0.10273490179183356,0.05063772912460758
WA,0.1227267155310865,0.033420810177025154
WI,0.1058789616945621,0.0834599289973781
WV,0.018177378039311066,0.0335944752040858
WY,9.559487543121433e-05,0.06448377531254787